### ISSUE TITLE
Harvesting issues

### ISSUE THREAD

**Issue by joseph6x** [ucuenca/redi#8]
ORCID property (http://purl.org/spar/scoro/hasORCID) missing in some resources of Scopus provider graph.
Example:
http://api.elsevier.com/content/author/author_id/6506281895

**Comment by cuent** [comment]
Commit https://github.com/ucuenca/redi/commit/95dc8369306a219aedef77197894d993c681ebfb#diff-2bd212fd5078967a6494bda8b9e5d31f solves the issue
